version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: pcms-db
      MYSQL_USER: pcms-user
      MYSQL_PASSWORD: pcms-password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
