version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: motor-busca-sphere-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
