CREATE TABLE demands (
    uuid CHAR(36) PRIMARY KEY,
    patient_uuid CHAR(36) NOT NULL,
    demand_description TEXT NOT NULL,
    problem_history TEXT,
    symptoms TEXT,
    treatment_goals TEXT,
    impact_on_life TEXT,
    previous_attempts TEXT,
    social_support TEXT,
    aggravating_factors TEXT,
    treatment_expectations TEXT,
    motivation_for_change TEXT,
    medication TEXT,
    other_therapies TEXT,
    additional_observations TEXT,
    current_feeling_id INT,
    feeling_intensity TINYINT CHECK (feeling_intensity BETWEEN 0 AND 10),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_uuid) REFERENCES patients(uuid),
    FOREIGN KEY (current_feeling_id) REFERENCES feelings(id),
    INDEX idx_patient_uuid (patient_uuid)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;